### ISSUE TITLE
CTRL+F (search) doesn't work on text editor (Plain text editor app)

### ISSUE THREAD

**Issue by kralizeck** [nextcloud/files_texteditor#184]
### Steps to reproduce
- Create a new text file from web interface. Or upload one.
- Fill it with some text lines.
- Try to search pressing Ctrl+F

### Expected behaviour
In editor top-right should appears a box to search text

### Actual behaviour
Nothing happens

## Server configuration detail

**Operating system:** FreeBSD 12.0-RELEASE-p10 FreeBSD 12.0-RELEASE-p10 GENERIC amd64

**Webserver:** nginx

**Database:** mysql 5.7.27

**PHP version:** 

7.2.22
Modules loaded: Core, date, libxml, pcre, Reflection, SPL, hash, session, cgi-fcgi, standard, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, filter, ftp, gd, gettext, gmp, mysqlnd, iconv, imagick, intl, json, ldap, exif, mcrypt, mysqli, openssl, pcntl, PDO, posix, SimpleXML, sockets, sodium, sqlite3, tokenizer, xml, xmlwriter, zip, zlib, imap, PDFlib, pdo_mysql, pdo_sqlite, Phar, redis, xmlreader, xmlrpc, Zend OPcache

**Nextcloud version:** 16.0.4 - 16.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** nextcloud.com

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - bruteforcesettings: 1.4.0
 - calendar: 1.7.1
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.3
 - dav: 1.9.2
 - encryption: 2.4.0
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_external: 1.7.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - nextcloud_announcements: 1.5.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - support: 1.0.0
 - survey_client: 1.4.0
 - tasks: 0.11.3
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - bookmarks
 - files_accesscontrol
 - systemtags
 - user_ldap

**Comment by gary-kim** [comment]
Sorry, I thought it was the other editor.

**Comment by Pecadis** [comment]
Hi, i have upgraded to OC17 and used the texteditor v2.9.0 but ctrl+F still doesn't work

**Comment by tavinus** [comment]
Hi there!  
  
I have re-enabled this app because the new Text app was giving me all sorts of problems. But then I really miss the possibility to search in the text files. So I decided to investigate and was able to re-enable the `CTRL-F` search.  
  
From what I can understand, the search was lost when the [ace editor](https://ace.c9.io/) was migrated to the [brace webpack](https://github.com/thlorenz/brace). This was around Nextcloud 16.  
  
**Please note that I tested this on a Nextcloud 18.0.1 install,  
where I installed `files_texteditor` manually with**
```bash
sudo su - # get root shell
cd /var/www/nextcloud/apps/
git clone https://github.com/nextcloud/files_texteditor.git
cd files_texteditor/
git fetch
git checkout v18.0.1
chown -R www-data:www-data /var/www/nextcloud/apps/files_texteditor
```
  
I was able to find a [few issues about the searchbox](https://github.com/thlorenz/brace/issues?q=is%3Aissue+searchbox) at brace's repo.  
  
The fix is to include a require statement in the app.
```php
require('brace/ext/searchbox');
```
I am not familiar with Nextcloud packaging, nor webpacks, nor babel, nor npm, but spent a couple of hours researching and this is how I got it fixed in the `files_texteditor` app. Please let me know if there is an easier/better way to do this.  
  
First I needed to patch/edit the file `js/editor.js` to include the require call. However, the way brace is required/included is not trivial as it is called as a function at the middle of the code. So I had to add it inside the `_onEditorTrigger` function, after [Line 192](https://github.com/nextcloud/files_texteditor/blob/master/js/editor.js#L192), inside the `importAce().then()` call.  
  
**Before**
```php
	/**
	 * Handles the FileAction click event
	 */
	_onEditorTrigger: function (filename, context) {
		this.currentContext = context;
		this.file.name = filename;
		this.file.dir = context.dir;
		this.fileList = context.fileList;
		importAce().then((_ace) => {
			ace = _ace;
			this.loadEditor(
				Texteditor.$container,
				Texteditor.file
			);
			history.pushState({
				file: filename,
				dir: context.dir
			}, 'Editor', '#filestexteditor');
		});
	},
```
**After**
```php
	/**
	 * Handles the FileAction click event
	 */
	_onEditorTrigger: function (filename, context) {
		this.currentContext = context;
		this.file.name = filename;
		this.file.dir = context.dir;
		this.fileList = context.fileList;
		importAce().then((_ace) => {
			// ADDED BY TAVINUS FOR SEARCHBOX
			require('brace/ext/searchbox');
			ace = _ace;
			this.loadEditor(
				Texteditor.$container,
				Texteditor.file
			);
			history.pushState({
				file: filename,
				dir: context.dir
			}, 'Editor', '#filestexteditor');
		});
	},
```
-------------------------------------
But this is not enough to make it work, since we need npm/webpack to "recompile" the build folder.  
  
To do this, first we need `nodejs` and `npm` running at the machine.  
  
On a Debian 10 Buster I just used
```
sudo apt-get update
sudo apt-get install nodejs npm
```
*NPM complains about the nodejs version at every run, but seems to work ok*  
  
## Option 1 - Run as root
Init and build
```bash
cd /var/www/nextcloud/apps/files_texteditor # adjust folder
sudo npm install
sudo npm run-script build
```
*Some docs mention `npm build` instead of `npm run-script build`, but only the first worked here.*  
  
Fix permissions
```
sudo chown -R www-data:www-data /var/www/nextcloud/apps/files_texteditor
```  
  
## Option 2 - Run as user `www-data`
*Your linux distro may use another user for the webserver*

If you want to run npm as the `www-data` user and at the `/var/www/nextcloud/apps/files_texteditor` folder, we will first need to create and set permission to the `/var/www/.npm` folder  
*(this assumes the "home" folder for the user www-data is set to `/var/www`)*
```
sudo mkdir /var/www/.npm
sudo chown www-data:www-data /var/www/.npm
```

Then we init and build
```bash
cd /var/www/nextcloud/apps/files_texteditor # adjust folder
sudo -u www-data npm install
sudo -u www-data npm run-script build
```
*Some docs mention `npm build` instead of `npm run-script build`, but only the first worked here.*  
  
---------------------------------------------
## Conclusion
Anyways, I am glad to have search back there.  
This was driving me nuts!  
  
![image](https://user-images.githubusercontent.com/8039413/76346677-27eb0280-62e4-11ea-8c24-d9fa235426eb.png)

Cheers!  
Gus
