### ISSUE TITLE
Middle click paste support

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/files_texteditor#20]
Using text editor to grab records of commands issued in a console - but middle click paste (FF50) doesn't work, generates some of character that doesn't appear to be in the file in a normal sense, more of a visual artefact, with its own cursor associated:
![image](https://cloud.githubusercontent.com/assets/2872580/21099509/83f4f62c-c066-11e6-83a4-8c2d4e74bb00.png)

Select to copy does not seem to work either.

**Comment by willwesley** [comment]
@putt1ck Do you still have this problem? I was having a similar issue on FF91 and it turned out to be that I had disabled `dom.event.clipboardevents.enabled` option in my `about:config`. Turning that back to `true` fixed most of my problems (selecting still doesn't put text onto my middle-click clipboard, but I can middle-click paste into the editor and the regular copy and paste functionality seems to work).

**Comment by putt1ck** [comment]
Concur middle click paste is functional for me, must have been fixed in one of the editor updates along the way (my FF installs do not have that setting disabled).
